extends: default
yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'
ignore:
  - cmip6-cmor-tables/
  - CMIP7_DReq_Software/
  - CMIP7-CVs/
  - tests/fixtures/stub_data/
rules:
  line-length:
    max: 170
    level: warning
  document-start: disable
  truthy: disable
  comments:
    min-spaces-from-content: 1
